name: Crash
title: "Crash Report: "
description: Report a crash that occurred while using the engine.
labels: [major bug]
type: Bug
body:
  - type: checkboxes
    attributes:
      label: Issue Checklist
      description: Be sure to complete these steps to increase the chances of your issue being addressed!
      options:
        # - label: I have read the [Contributing Guide](https://github.com/FunkinCrew/Funkin/blob/main/docs/CONTRIBUTING.md)
        - label: I have checked the issues/discussions pages to see if my issue has already been reported.
        - label: I have properly titled my issue.
        - label: I did not have any mods installed when I encountered this issue.

  - type: textarea
    attributes:
      label: What's your question?
      placeholder: Well, how do I ____?
    validations:
      required: true