name: Crash
title: "Crash Report: "
description: Report a crash that occurred while using the engine.
labels: [major bug]
type: Bug
body:
  - type: checkboxes
    attributes:
      label: Issue Checklist
      description: Be sure to complete these steps to increase the chances of your issue being addressed!
      options:
        # - label: I have read the [Contributing Guide](https://github.com/FunkinCrew/Funkin/blob/main/docs/CONTRIBUTING.md)
        - label: I have checked the issues/discussions pages to see if my issue has already been reported.
        - label: I have properly titled my issue.
        - label: I did not have any mods enabled when I encountered this issue.

  - type: input
    attributes:
      label: |
        What version of the engine are you using?
        If it's an action build, please provide a link or something similar.
      placeholder: "v0.3-pre-alpha action 2826 [example link]"
    validations:
      required: true

  - type: textarea
    attributes:
      label: |
        Describe the crash as clearly as possible.
        Give context to what led you to this crash.
      placeholder: |
        I did ____ and ____, as well as ____.
        Then ____ happened when I ____ which crashed my game.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Crash Log
      placeholder: |
        The crash log should be located in the crash folder at the root of the engine.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: How are you modding the engine?
      description: Check the boxes to state what things you've done.
      multiple: true
      options:
        - I edited the **source code**. # unsure how to handle this
        - I used **haxe scripting**.
        - I used **lua scripting**.
        - I haven't changed anything!
    validations:
      required: true

  - type: dropdown
    attributes:
      label: What platform are you running the engine on?
      options:
        - Windows
        - Linux
        - Mac
        # - Android
        # - IOS
    validations:
      required: true