name: Feature Request
description: Request something you want put in the engine!
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: |
        What feature do you want to get added to the **base** engine?
        Why do you think we should consider adding this?
    validations:
      required: true
