name: Question
description: Ask something related to the engine.
labels: [question]
body:
  - type: textarea
    attributes:
      label: What's your question?
      placeholder: Well, how do I ____?
    validations:
      required: true