name: Question
description: Ask something related to the engine.You can also do this here! --> [https://discord.com/channels/1302332813634174996/1306267515743244288](https://discord.com/channels/1302332813634174996/1306267515743244288)
labels: [question]
body:
  - type: textarea
    attributes:
      label: What's your question?
      placeholder: Well, how do I ____?
    validations:
      required: true